# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c7e2195a8a658b981b68bcdc72f77e3dadd359b1c9cd4a6c884d039d1637f56f8671a8fa15e44813f3be5127a74feae692eff2f2a26dcdffe92047e7cff5fae

test:
  secret_key_base: 1010827168a9ef89191c69d22560d30bcaf2275800f28542761f48a40facf3c54352ce14727a77ca405d21f4949fcaf4f594792d2a2dd66b80fd3c3e472a5ba0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
